channels:
  - conda-forge
dependencies:
  - python
  - c-compiler
  - cxx-compiler
  - make
  - git
  - git-lfs
  - ipython
  - cmake
  - pyyaml
  - pyzmq
  - parse
  - click
  - numpy
  - boost
  - bzip2
  - zeromq
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinxcontrib-napoleon
  - breathe
  - pyserial
  - p4p
  - sqlalchemy
  - pydm>=1.18.0
  - matplotlib
  - pytest
  - pytest-cov
  - pytest-xdist
  - pyqt>=5.15
  - qtpy>=2.0
  - pyqtgraph>=0.13
