channels:
  - conda-forge
dependencies:
  - python>=3.7
  - gcc_linux-64
  - gxx_linux-64
  - make
  - git
  - git-lfs
  - ipython
  - cmake
  - pyyaml
  - pyzmq
  - parse
  - click
  - numpy
  - boost
  - bzip2
  - zeromq
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - pyserial
  - p4p
  - sqlalchemy
  - pydm>=1.18.0
  - matplotlib
  - pytest
  - pytest-cov
  - pyqt=5.12
