/**
 * ----------------------------------------------------------------------------
 * Company    : SLAC National Accelerator Laboratory
 * ----------------------------------------------------------------------------
 * Description:
 * Memory master interface.
 * ----------------------------------------------------------------------------
 * This file is part of the rogue software platform. It is subject to
 * the license terms in the LICENSE.txt file found in the top-level directory
 * of this distribution and at:
 *    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
 * No part of the rogue software platform, including this file, may be
 * copied, modified, propagated, or distributed except according to the terms
 * contained in the LICENSE.txt file.
 * ----------------------------------------------------------------------------
 **/
#ifndef __ROGUE_INTERFACES_MEMORY_MASTER_H__
#define __ROGUE_INTERFACES_MEMORY_MASTER_H__
#include "rogue/Directives.h"

#include <stdint.h>

#include <map>
#include <memory>
#include <string>
#include <thread>
#include <vector>

#include "rogue/Logging.h"

#ifndef NO_PYTHON
    #include <boost/python.hpp>
#endif

namespace rogue {
namespace interfaces {
namespace memory {

class Slave;
class Transaction;

/**
 * @brief Master endpoint for memory transactions.
 *
 * @details
 * `Master` initiates transactions on a memory bus tree. Each master connects to one
 * downstream `Slave` or `Hub`, and hub levels may be chained. Hub offsets are applied
 * to transaction addresses as requests propagate toward leaf slave devices.
 */
class Master {
    friend class Transaction;

  private:
    /** Map type for tracking in-flight transactions by transaction ID. */
    typedef std::map<uint32_t, std::shared_ptr<rogue::interfaces::memory::Transaction> > TransactionMap;

    /** In-flight transaction map. */
    TransactionMap tranMap_;

    /** Downstream slave/hub target for forwarded requests. */
    std::shared_ptr<rogue::interfaces::memory::Slave> slave_;

    /** Default timeout for future transactions. */
    struct timeval sumTime_;

    /** Mutex protecting shared master state. */
    std::mutex mastMtx_;

    /** Error string from the last completed transaction sequence. */
    std::string error_;

    /** Logger for master activity. */
    std::shared_ptr<rogue::Logging> log_;

  public:
    /**
     * @brief Creates a memory master instance.
     *
     * @details
     * Exposed as `rogue.interfaces.memory.Master()` in Python.
     * This static factory is the preferred construction path when the object
     * is shared across Rogue graph connections or exposed to Python.
     * It returns `std::shared_ptr` ownership compatible with Rogue pointer typedefs.
     *
     * @return Shared pointer to the created master.
     */
    static std::shared_ptr<rogue::interfaces::memory::Master> create();

    /** @brief Registers this type with Python bindings. */
    static void setup_python();

    /**
     * @brief Constructs a memory master instance.
     *
     * @details
     * This constructor is a low-level C++ allocation path.
     * Prefer `create()` when shared ownership or Python exposure is required.
     */
    Master();

    /** @brief Destroys the memory master instance. */
    virtual ~Master();

    /** @brief Stops the interface and releases runtime resources. */
    virtual void stop();

    /**
     * @brief Sets the downstream slave or hub.
     *
     * @details
     * Transactions generated by this master are forwarded to this target. The target
     * may be a leaf slave or a hub that forwards to lower levels.
     * Exposed as `_setSlave()` in Python.
     *
     * @param slave Downstream slave or hub pointer.
     */
    void setSlave(std::shared_ptr<rogue::interfaces::memory::Slave> slave);

    /**
     * @brief Returns the configured downstream slave or hub.
     *
     * @details Exposed as `_getSlave()` in Python.
     *
     * @return Downstream slave or hub pointer.
     */
    std::shared_ptr<rogue::interfaces::memory::Slave> getSlave();

    /**
     * @brief Queries the downstream slave ID.
     *
     * @details
     * Forwards the request to the lowest-level slave servicing this master path.
     * This is used to determine which masters share an address space.
     * Exposed as `_reqSlaveId()` in Python.
     *
     * @return Unique 32-bit slave ID.
     */
    uint32_t reqSlaveId();

    /**
     * @brief Queries the downstream slave name.
     *
     * @details
     * Forwards the request to the lowest-level slave servicing this master path.
     * This allows the system to determine which memory Masters share an address space.
     * Exposed as `_reqSlaveName()` in Python.
     *
     * @return Slave name string.
     */
    std::string reqSlaveName();

    /**
     * @brief Queries minimum access size in bytes for this interface path.
     *
     * @details
     * Request is forwared to the lowest-level slave to determine the minimum transaction size.
     * Exposed as `_reqMinAccess()` in Python.
     *
     * @return Minimum transaction size in bytes.
     */
    uint32_t reqMinAccess();

    /**
     * @brief Queries maximum access size in bytes for this interface path.
     *
     * @details
     * Request is forwared to the lowest-level slave to determine the maximum transaction size.
     * Exposed as `_reqMaxAccess()` in Python.
     *
     * @return Maximum transaction size in bytes.
     */
    uint32_t reqMaxAccess();

    /**
     * @brief Queries the address offset of the next downstream layer.
     *
     * @details
     * Returns the relative offset of the connected slave/hub and does not include
     * any local master offset. Exposed as `_reqAddress()` in Python.
     *
     * @return Downstream relative address offset.
     */
    uint64_t reqAddress();

    /**
     * @brief Returns the last transaction error string.
     *
     * @details Exposed as `_getError()` in Python.
     *
     * @return Error string for the last transaction sequence.
     */
    std::string getError();

    /**
     * @brief Clears the stored transaction error string.
     *
     * @details Exposed as `_clearError()` in Python.
     */
    void clearError();

    /**
     * @brief Sets the timeout value for future transactions.
     *
     * @details
     * Timeout controls how long the master waits for transaction completion.
     * Exposed as `_setTimeout()` in Python.
     *
     * @param timeout Timeout value in microseconds.
     *                A value of `0` leaves the current timeout unchanged.
     */
    void setTimeout(uint64_t timeout);

    /**
     * @brief Starts a new transaction.
     *
     * @details
     * Creates a transaction object and forwards it to the lowest-level slave in
     * the memory tree. The address is relative to the next layer offset and multiple
     * transactions may be pending simultaneously.
     * Not exposed to Python (see `reqTransactionPy`).
     *
     * @param address Relative 64-bit transaction address.
     * @param size Transaction size in bytes.
     * @param data Pointer to transaction data storage.
     * @param type Transaction type constant.
     * @return 32-bit transaction ID.
     */
    uint32_t reqTransaction(uint64_t address, uint32_t size, void* data, uint32_t type);

#ifndef NO_PYTHON

    /**
     * @brief Python variant of `reqTransaction`.
     *
     * @details
     * Uses a Python buffer-protocol object instead of a raw C++ data pointer.
     * Exposed to Python as `_reqTransaction()`.
     *
     * `p` may be any object exporting the buffer protocol (for example `bytearray`,
     * `bytes`, `memoryview`, or a contiguous NumPy array). For `Read`/`Verify`
     * transactions, `p` should be a writable contiguous buffer so returned data can
     * be written into it.
     *
     * @param address Relative 64-bit transaction address.
     * @param p Python buffer-protocol object containing transaction bytes.
     * @param size Transaction size in bytes.
     * @param offset Byte offset within `p`.
     * @param type Transaction type constant.
     * @return 32-bit transaction ID.
     */
    uint32_t reqTransactionPy(uint64_t address, boost::python::object p, uint32_t size, uint32_t offset, uint32_t type);

#endif

    /**
     * @brief Copies bits between two byte arrays.
     *
     * @details
     * Copies `size` bits from `srcData` starting at bit `srcLsb` into `dstData`
     * starting at bit `dstLsb`.
     *
     * Bit numbering is least-significant-bit-first within each byte (bit 0 is the
     * LSB of byte 0). The routine preserves destination bits outside the copied
     * range and supports arbitrary unaligned source/destination bit offsets.
     * When both offsets are byte-aligned, it uses a byte-copy fast path.
     *
     * This helper underpins variable packing/unpacking logic in the memory layer.
     * Exposed as `_copyBits()` in Python.
     *
     * @param dstData Destination byte array.
     * @param dstLsb Least-significant destination bit index.
     * @param srcData Source byte array.
     * @param srcLsb Least-significant source bit index.
     * @param size Number of bits to copy.
     */
    static void copyBits(uint8_t* dstData, uint32_t dstLsb, uint8_t* srcData, uint32_t srcLsb, uint32_t size);

#ifndef NO_PYTHON

    /**
     * @brief Python wrapper for `copyBits`.
     *
     * @details
     * Accepts Python buffer-protocol objects, validates bounds, and copies `size`
     * bits from `src` bit index `srcLsb` to `dst` bit index `dstLsb`.
     * Bit numbering is least-significant-bit-first within each byte.
     *
     * Exposed as `_copyBits()` in Python.
     *
     * @param dst Destination writable contiguous Python buffer.
     * @param dstLsb Least-significant destination bit index.
     * @param src Source Python buffer.
     * @param srcLsb Least-significant source bit index.
     * @param size Number of bits to copy.
     */
    static void copyBitsPy(boost::python::object dst,
                           uint32_t dstLsb,
                           boost::python::object src,
                           uint32_t srcLsb,
                           uint32_t size);

#endif

    /**
     * @brief Sets a contiguous bit range in a byte array.
     *
     * @details
     * Sets `size` bits to `1` in `dstData` starting at bit `lsb`.
     *
     * Bit numbering is least-significant-bit-first within each byte (bit 0 is the
     * LSB of byte 0). Bits outside the requested range are left unchanged. For
     * byte-aligned regions, it uses a byte-fill fast path.
     *
     * This helper is used to build masks such as overlap and verify masks.
     * Exposed as `_setBits()` in Python.
     *
     * @param dstData Destination byte array.
     * @param lsb Least-significant bit index to set.
     * @param size Number of bits to set.
     */
    static void setBits(uint8_t* dstData, uint32_t lsb, uint32_t size);

#ifndef NO_PYTHON

    /**
     * @brief Python wrapper for `setBits`.
     *
     * @details
     * Accepts a Python writable contiguous buffer and sets `size` bits to `1`
     * starting at bit `lsb`.
     * Bit numbering is least-significant-bit-first within each byte.
     *
     * Exposed as `_setBits()` in Python.
     *
     * @param dst Destination writable contiguous Python buffer.
     * @param lsb Least-significant bit index to set.
     * @param size Number of bits to set.
     */
    static void setBitsPy(boost::python::object dst, uint32_t lsb, uint32_t size);

#endif

    /**
     * @brief Tests whether any bit in a range is set.
     *
     * @details
     * Checks `size` bits in `srcData` starting at bit `lsb` and returns `true` if
     * at least one bit is `1`.
     *
     * Bit numbering is least-significant-bit-first within each byte (bit 0 is the
     * LSB of byte 0). This helper is commonly used for overlap and mask checks.
     * Exposed as `_anyBits()` in Python.
     *
     * @param srcData Source byte array to check.
     * @param lsb Least-significant bit index to check.
     * @param size Number of bits to check.
     * @return `true` if any bit in the range is set; otherwise `false`.
     */
    static bool anyBits(uint8_t* srcData, uint32_t lsb, uint32_t size);

#ifndef NO_PYTHON

    /**
     * @brief Python wrapper for `anyBits`.
     *
     * @details
     * Accepts a Python buffer-protocol object and checks whether any bit is set
     * in the requested range.
     *
     * Exposed as `_anyBits()` in Python.
     *
     * @param src Source Python buffer to check.
     * @param lsb Least-significant bit index to check.
     * @param size Number of bits to check.
     * @return `true` if any bit in the range is set; otherwise `false`.
     */
    static bool anyBitsPy(boost::python::object src, uint32_t lsb, uint32_t size);

#endif

#ifndef NO_PYTHON

    /** @brief Supports `>>` operator usage from Python. */
    void rshiftPy(boost::python::object p);

#endif

    /** @brief Connects this master to a slave via stream chaining operator. */
    std::shared_ptr<rogue::interfaces::memory::Slave>& operator>>(
        std::shared_ptr<rogue::interfaces::memory::Slave>& other);

  protected:
    /** @brief Starts an internal transaction from an existing transaction object. */
    uint32_t intTransaction(std::shared_ptr<rogue::interfaces::memory::Transaction> tran);

  public:
    /**
     * @brief Waits for transaction completion or timeout.
     *
     * @details
     * Passing `0` waits for all currently pending transactions.
     * Exposed as `_waitTransaction()` in Python.
     *
     * @param id Transaction ID to wait for, or `0` for all.
     */
    void waitTransaction(uint32_t id);
};

/** @brief Shared pointer alias for `Master`. */
typedef std::shared_ptr<rogue::interfaces::memory::Master> MasterPtr;
}  // namespace memory
}  // namespace interfaces
}  // namespace rogue

#endif
