###############################################################################################
# Notes for checking if conda solution exist before doing the actual conda build
###############################################################################################
# conda render conda-recipe --variants "{python: 3.10, python_abi: '3.10 *_cp310'}"
# conda render conda-recipe --variants "{python: 3.11, python_abi: '3.11 *_cp311'}"
# conda render conda-recipe --variants "{python: 3.12, python_abi: '3.12 *_cp312'}"
# conda render conda-recipe --variants "{python: 3.13, python_abi: '3.13 *_cp313'}"
###############################################################################################

# Define the python variants to be built
python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13

# Lock to CPython ABI, not PyPy
python_abi:
  - 3.10 *_cp310
  - 3.11 *_cp311
  - 3.12 *_cp312
  - 3.13 *_cp313

zip_keys:
  - [python, python_abi, cpython]

pin_run_as_build:
  python: {min_pin: x.x, max_pin: x.x}
  numpy:  {min_pin: x.x, max_pin: x.x}
