export EPICS_BASE_LIB=${CONDA_PREFIX}/epics/lib/${EPICS_HOST_ARCH}
export EPICS_PCAS_LIB=${CONDA_PREFIX}/pcas/lib/${EPICS_HOST_ARCH}
export LD_LIBRARY_PATH=${EPICS_BASE_LIB}:${EPICS_PCAS_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
