#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# Title      : ROGUE Perf Harness Campaign Report
# ----------------------------------------------------------------------------
# This file is part of the rogue software platform. It is subject to
# the license terms in the LICENSE.txt file found in the top-level directory
# of this distribution and at:
#    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
# No part of the rogue software platform, including this file, may be
# copied, modified, propagated, or distributed except according to the terms
# contained in the LICENSE.txt file.
# ----------------------------------------------------------------------------

"""Aggregates the committed tests/perf/_perf_harness.py records under
docs/plans/perf-ci-hardening/harness-runs/ into a byte-stable campaign report
and a versioned JSON sidecar, modelled structurally on
scripts/probe_capability_report.py rather than extending it: the harness
records and the probe records are shaped differently and evolve on
independent schedules, so a shared aggregator would couple two things that
have no reason to change together.
"""

from __future__ import annotations

import argparse
import json
import math
import statistics
import sys
from pathlib import Path
from typing import Any

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import perf_noise_report  # noqa: E402  (flat sibling import, path inserted above)
import perf_tier_registry  # noqa: E402  (flat sibling import, path inserted above)

# tests/perf/_perf_harness.py is the source of truth for the rejection-threshold derivation
# strings the contamination section quotes below (MAD_BAND_DERIVATION and
# STEAL_DELTA_THRESHOLD_DERIVATION) and for DUAL_CLOCK_METRIC_NAMES, the flattening section's
# four candidate base metrics. Imported by bare module name (never `tests.perf._perf_harness`)
# so this module stays runnable on a machine where a stray top-level `tests` package shadows
# this repository's own `tests/` namespace package.
TESTS_PERF_DIR = SCRIPTS_DIR.parent / "tests" / "perf"
if str(TESTS_PERF_DIR) not in sys.path:
    sys.path.insert(0, str(TESTS_PERF_DIR))
import _perf_harness  # noqa: E402  (flat sibling import, path inserted above)


SIDECAR_VERSION = 1

# scripts/perf_harness_runner.py's HARNESS_RUN_SCHEMA_VERSION: the aggregated run-record's own
# top-level key, distinct from tests/perf/_perf_harness.py's per-benchmark
# "harness_schema_version" (the raw per-module sibling files the aggregator itself reads and
# folds in, never committed to docs/plans/perf-ci-hardening/harness-runs/ directly). A real
# campaign dispatch showed this module originally checked the per-benchmark key name here,
# which meant every real aggregated record (the only kind scripts/perf_harness_campaign.py's
# cmd_collect writes, once it collects the correct run-record.json sibling) failed this check
# and was silently treated as an unrecognized schema version.
EXPECTED_HARNESS_SCHEMA_VERSION = 1

DEFAULT_RUNS_DIR = "docs/plans/perf-ci-hardening/harness-runs"
DEFAULT_OUT_MD = "docs/plans/perf-ci-hardening/CAMPAIGN-REPORT.md"
DEFAULT_OUT_JSON = "docs/plans/perf-ci-hardening/campaign-report.json"
DEFAULT_NOISE_FLOOR_PATH = "docs/plans/perf-ci-hardening/noise-floor.json"

# Named here as a constant, not a live filesystem read, so this report's byte-stability
# contract is preserved even though the reconciliation document itself is not regenerated by
# this script: HARNESS-SETUP.md carries the per-criterion and per-requirement reconciliation
# this report's own sections feed but do not restate.
RECONCILIATION_DOC = "docs/plans/perf-ci-hardening/HARNESS-SETUP.md"

# Fallback values used only when Phase 1's noise-floor.json sidecar is missing or malformed,
# kept identical to perf_noise_report.py's own defaults so this report produces the same
# numbers whether or not that sidecar is readable.
FALLBACK_MIN_N = perf_noise_report.DEFAULT_MIN_N
FALLBACK_MDE_Z = perf_noise_report.DEFAULT_MDE_Z
FALLBACK_MDE_GATE_PCT = perf_noise_report.DEFAULT_MDE_GATE_PCT

# A metric registered in scripts/perf_tier_registry.py but never carrying a tier_candidate on
# any accepted record's own emitted metric entry: no candidate tier can be reported for it
# without reading the live registry, which this report's byte-stability contract forbids (see
# build_metric_section below): a later registry edit must never change a byte of an
# already-committed report.
TIER_CANDIDATE_NOT_RECORDED = "not-recorded"

# The binding tier/verdict for a metric the cross-CPU-model invariance section has not yet
# computed a verdict for: never falls back to the candidate tier, since a candidate tier is
# only a hypothesis pending cross-model comparison, not evidence.
NOT_YET_DETERMINED = "not-yet-determined"

# A field present but not a usable string (or entirely absent), distinct from
# INSUFFICIENT_SAMPLES: this is a missing/unreadable field, not a small sample count.
MISSING_FIELD = "missing"

# Cross-CPU-model invariance verdicts: the same no-tolerance min-equals-max bar
# scripts/probe_instruments.py's repeatability_verdict applies within a single host,
# extended here across every observed CPU model.
CROSS_MODEL_VERDICT_BIT_IDENTICAL = "bit-identical"
CROSS_MODEL_VERDICT_DEMOTED = "demoted-to-tier-2"
CROSS_MODEL_VERDICT_WITHIN_RUN_DEMOTED = "demoted-to-tier-2-within-run"

# A metric whose registry direction is not invariant: an exact minimum-equals-maximum
# comparison is meaningless for a continuous metric (there is nothing "invariant" for it to
# be), so it is never compared and its binding tier trivially equals its candidate tier
# rather than being computed.
NOT_APPLICABLE_NOT_INVARIANT = "not-applicable-non-invariant-metric"

# The three distinct CPU models Phase 2's real campaign observed
# (docs/plans/perf-ci-hardening/CAPABILITY-MATRIX.md, Coverage section), used here only to
# state this campaign's coverage honestly against that prior baseline -- never to gate
# anything in this phase.
PHASE_2_OBSERVED_CPU_MODELS: tuple[str, ...] = (
    "AMD EPYC 7763 64-Core Processor",
    "AMD EPYC 9V74 80-Core Processor",
    "INTEL(R) XEON(R) PLATINUM 8573C",
)


def load_noise_floor_parameters(path: Path) -> dict[str, Any]:
    """Read min_n, mde_z, and mde_gate_pct from Phase 1's noise-floor.json sidecar's
    `parameters` block, rather than hardcoding any of them here.

    Never raises: an unreadable file, malformed JSON, a non-mapping payload, or a missing
    `parameters` block returns the documented fallback values with `loaded` false, so this
    report still runs before or without that Phase 1 artifact -- following
    scripts/env_fingerprint.py's `_try` never-raise sentinel discipline.
    """
    result: dict[str, Any] = {
        "source_file": str(path),
        "min_n": FALLBACK_MIN_N,
        "mde_z": FALLBACK_MDE_Z,
        "mde_gate_pct": FALLBACK_MDE_GATE_PCT,
        "loaded": False,
    }
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return result
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        return result
    if not isinstance(payload, dict):
        return result
    parameters = payload.get("parameters")
    if not isinstance(parameters, dict):
        return result
    for key in ("min_n", "mde_z", "mde_gate_pct"):
        if key in parameters:
            result[key] = parameters[key]
    result["loaded"] = True
    return result


# Loaded once at import time, exactly like DEFAULT_EXPECTED_TREE_HASH below is a fixed value
# baked into CANONICAL_COMMAND: the minimum sample count, the provisional MDE z value, and the
# provisional gate percentage all come from Phase 1's committed sidecar rather than a literal
# number written at a use site in this module.
_NOISE_FLOOR_DEFAULTS = load_noise_floor_parameters(Path(DEFAULT_NOISE_FLOOR_PATH))

DEFAULT_MIN_N = _NOISE_FLOOR_DEFAULTS["min_n"]
DEFAULT_PROVISIONAL_MDE_Z = _NOISE_FLOOR_DEFAULTS["mde_z"]
DEFAULT_MDE_GATE_PCT = _NOISE_FLOOR_DEFAULTS["mde_gate_pct"]

# The frozen perf-harness/campaign-v3 branch's tree hash, recorded in
# docs/plans/perf-ci-hardening/HARNESS-SETUP.md. Every committed harness
# run's run.git_tree_hash traces to this value. Re-pointed here a second
# time, from perf-harness/campaign-v2's hash
# (6b74f79118161d744d1969808ef3020a3844a570, itself a re-point from the
# original perf-harness/campaign tracer-era hash
# 5f58782c97b5be8e740c69bcbc987d630fe0bf6f), once the Slave binding change
# and the two new coverage benchmark modules moved the measured tree. The
# superseded population pinned to the previous hash is archived under
# docs/plans/perf-ci-hardening/harness-runs-superseded-6b74f791/.
DEFAULT_EXPECTED_TREE_HASH = "e9e53cdb0f493b1faf1f1d11c4eb1fdbc6144b03"

TREE_HASH_MISMATCH = "tree-hash-mismatch"
INSUFFICIENT_SAMPLES = "insufficient-samples"

# Marks a harness run dispatched with its injected-load input set, so a
# report over the clean campaign population never silently mixes a
# synthetic-load demonstration run in with the measurements it is meant to
# be compared against. Used at the one call site below rather than as a
# bare string.
INJECTED_DEMONSTRATION = "injected-load-demonstration"

# Two-sided 95% confidence (Z_ALPHA_2) and 80% power (Z_BETA), the standard
# minimum-detectable-effect normal approximation constants.
Z_ALPHA_2 = 1.959963985
Z_BETA = 0.8416212336

CANONICAL_COMMAND = (
    "python3 scripts/perf_campaign_report.py "
    f"--runs-dir {DEFAULT_RUNS_DIR} --expected-tree-hash {DEFAULT_EXPECTED_TREE_HASH} "
    f"--min-n {DEFAULT_MIN_N} --out-md {DEFAULT_OUT_MD} --out-json {DEFAULT_OUT_JSON}"
)


def fmt_float(value: Any) -> str:
    """Fixed float formatting shared by every numeric cell in this module,
    matching scripts/perf_noise_report.py's own fmt_float convention so byte
    stability survives identical inputs regardless of underlying float repr.
    """
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, (int, float)):
        return f"{value:.6g}"
    return str(value)


def two_sample_mde_pct(cv: float, n: int) -> float:
    """Two-sample minimum-detectable-effect percentage: the normal
    approximation with both a confidence and a power term, unlike
    scripts/perf_noise_report.py's provisional_mde, which carries no power
    term."""
    return (Z_ALPHA_2 + Z_BETA) * math.sqrt(2.0 / n) * cv * 100.0


def load_harness_run(path: Path) -> dict[str, Any] | None:
    """Load and validate one committed harness-run JSON file.

    Returns None on any decode failure, a non-mapping payload, or an
    unrecognized `harness_run_schema_version`, so the caller can skip and
    count a malformed record instead of crashing. Never raises.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        return None
    if not isinstance(payload, dict):
        return None
    schema_version = payload.get("harness_run_schema_version")
    if not isinstance(schema_version, int) or schema_version != EXPECTED_HARNESS_SCHEMA_VERSION:
        return None
    return payload


def is_injected_load_run(record: dict[str, Any]) -> bool:
    """True when `record.run.injected_load` is the literal string `"true"`:
    tests/perf/_perf_harness.py's build_harness_record stamps this field from the
    HARNESS_INJECTED_LOAD environment variable as a string, never a bool."""
    run_info = record.get("run")
    run_info = run_info if isinstance(run_info, dict) else {}
    injected = run_info.get("injected_load")
    return isinstance(injected, str) and injected.strip().lower() == "true"


def build_population(paths: list[Path], expected_tree_hash: str | None) -> dict[str, Any]:
    """Classify every committed harness-run file into the accepted
    population, a decode/schema-version skip, or a tree-hash-mismatch
    rejection.

    Paths are always processed in sorted (filename) order, so the accepted
    population is identical no matter how the filesystem listed the runs
    directory. A malformed file and a tree-hash mismatch are counted
    separately: a malformed file is a tooling problem, while a mismatched
    tree hash means the run measured different code and is not a member of
    this population at all. Neither is ever silently dropped.
    """
    accepted: list[dict[str, Any]] = []
    records_skipped = 0
    skipped_reasons: list[dict[str, Any]] = []
    records_rejected = 0
    rejected_reasons: list[dict[str, Any]] = []

    for path in sorted(paths, key=lambda p: p.name):
        record = load_harness_run(path)
        if record is None:
            records_skipped += 1
            skipped_reasons.append({
                "path": str(path),
                "reason": "unreadable, malformed JSON, or an unrecognized harness_run_schema_version",
            })
            continue

        run_info = record.get("run")
        run_info = run_info if isinstance(run_info, dict) else {}
        observed_tree_hash = run_info.get("git_tree_hash")

        if expected_tree_hash is not None and observed_tree_hash != expected_tree_hash:
            records_rejected += 1
            rejected_reasons.append({
                "path": str(path),
                "reason": TREE_HASH_MISMATCH,
                "observed_tree_hash": observed_tree_hash,
                "expected_tree_hash": expected_tree_hash,
            })
            continue

        record = dict(record)
        record["_run_id"] = path.stem
        accepted.append(record)

    return {
        "accepted": accepted,
        "records_skipped": records_skipped,
        "skipped_reasons": skipped_reasons,
        "records_rejected": records_rejected,
        "rejected_reasons": rejected_reasons,
    }


def _collect_metric_samples(records: list[dict[str, Any]], metric_name: str) -> list[float]:
    """Every clean numeric sample recorded for `metric_name` across every
    benchmark entry of every accepted record, in record then sample order.
    A non-numeric sample (the counter-regressed sentinel string) is excluded
    rather than coerced."""
    samples: list[float] = []
    for record in records:
        benchmarks = record.get("benchmarks")
        if not isinstance(benchmarks, dict):
            continue
        for benchmark_entry in benchmarks.values():
            if not isinstance(benchmark_entry, dict):
                continue
            metrics = benchmark_entry.get("metrics")
            if not isinstance(metrics, dict):
                continue
            metric_entry = metrics.get(metric_name)
            if not isinstance(metric_entry, dict):
                continue
            for sample in metric_entry.get("samples", []):
                if isinstance(sample, (int, float)) and not isinstance(sample, bool):
                    samples.append(float(sample))
    return samples


def _collect_metric_tier_candidates(records: list[dict[str, Any]], metric_name: str) -> list[int]:
    """Every `tier_candidate` value recorded on `metric_name`'s own metric entry across
    every benchmark of every record, in record-then-benchmark-name order. Benchmarks are
    iterated in sorted key order so this is deterministic regardless of dict insertion
    order. `tier_candidate` is stamped by tests/perf/_perf_harness.py's measure_benchmark
    at emission time on every metric entry it produces, whether the metric's status is
    "ok" or "inconclusive" -- so this is available whenever the metric was ever measured
    at all, never read from the live registry."""
    values: list[int] = []
    for record in records:
        benchmarks = record.get("benchmarks")
        if not isinstance(benchmarks, dict):
            continue
        for bench_name in sorted(benchmarks):
            entry = benchmarks[bench_name]
            if not isinstance(entry, dict):
                continue
            metrics = entry.get("metrics")
            if not isinstance(metrics, dict):
                continue
            metric_entry = metrics.get(metric_name)
            if not isinstance(metric_entry, dict):
                continue
            tier_value = metric_entry.get("tier_candidate")
            if isinstance(tier_value, int) and not isinstance(tier_value, bool):
                values.append(tier_value)
    return values


def _collect_metric_status_reasons(records: list[dict[str, Any]], metric_name: str) -> list[str]:
    """The sorted, deduplicated set of non-null `reason` strings recorded on
    `metric_name`'s own metric entry across every benchmark of every record (typically
    REASON_GUARD_EXCEEDED or REASON_INSUFFICIENT_CLEAN_SAMPLES from
    tests/perf/_perf_harness.py's measure_benchmark)."""
    reasons: set[str] = set()
    for record in records:
        benchmarks = record.get("benchmarks")
        if not isinstance(benchmarks, dict):
            continue
        for bench_name in sorted(benchmarks):
            entry = benchmarks[bench_name]
            if not isinstance(entry, dict):
                continue
            metrics = entry.get("metrics")
            if not isinstance(metrics, dict):
                continue
            metric_entry = metrics.get(metric_name)
            if not isinstance(metric_entry, dict):
                continue
            reason = metric_entry.get("reason")
            if isinstance(reason, str):
                reasons.add(reason)
    return sorted(reasons)


def _cpu_model_of(record: dict[str, Any]) -> str:
    """The recorded `environment.cpu_model` string, or MISSING_FIELD when absent or not
    a string -- the cross-CPU-model grouping key, derived from the record's own data
    rather than external fleet documentation (matching
    probe_capability_report._host_model_key's derivation pattern)."""
    environment = record.get("environment")
    environment = environment if isinstance(environment, dict) else {}
    cpu_model = environment.get("cpu_model")
    return cpu_model if isinstance(cpu_model, str) and cpu_model else MISSING_FIELD


def _collect_metric_samples_by_benchmark_and_model(
    records: list[dict[str, Any]], metric_name: str,
) -> dict[tuple[str, str], list[float]]:
    """Every clean numeric sample recorded for `metric_name`, grouped by
    (benchmark_name, cpu_model) rather than pooled across benchmarks. This is the grouping
    key the cross-CPU-model invariance comparison must use: pooling every benchmark's
    samples for a metric into one list before comparing (the prior
    `_collect_metric_samples_by_model` behaviour) meant a metric collected on several
    benchmarks with legitimately differing counts could never pass an exact-equality bar
    however deterministic each individual benchmark's cell was. Records are walked in
    population order and each record's own benchmarks in sorted name order, matching the
    other per-metric collectors' iteration discipline."""
    by_benchmark_and_model: dict[tuple[str, str], list[float]] = {}
    for record in records:
        model = _cpu_model_of(record)
        benchmarks = record.get("benchmarks")
        if not isinstance(benchmarks, dict):
            continue
        for bench_name in sorted(benchmarks):
            entry = benchmarks[bench_name]
            if not isinstance(entry, dict):
                continue
            metrics = entry.get("metrics")
            if not isinstance(metrics, dict):
                continue
            metric_entry = metrics.get(metric_name)
            if not isinstance(metric_entry, dict):
                continue
            for sample in metric_entry.get("samples", []):
                if isinstance(sample, (int, float)) and not isinstance(sample, bool):
                    by_benchmark_and_model.setdefault((bench_name, model), []).append(float(sample))
    return by_benchmark_and_model


def _collect_within_run_demotions(
    records: list[dict[str, Any]], metric_name: str,
) -> list[dict[str, Any]]:
    """Every within-run bit-identical failure tests/perf/_perf_harness.py's
    measure_benchmark already recorded for `metric_name`: a `tier_demoted_to`
    Tier 2 stamped on the metric entry itself, with its observed min/max/spread."""
    demotions: list[dict[str, Any]] = []
    for record in records:
        run_id = record.get("_run_id", MISSING_FIELD)
        benchmarks = record.get("benchmarks")
        if not isinstance(benchmarks, dict):
            continue
        for bench_name in sorted(benchmarks):
            entry = benchmarks[bench_name]
            if not isinstance(entry, dict):
                continue
            metrics = entry.get("metrics")
            if not isinstance(metrics, dict):
                continue
            metric_entry = metrics.get(metric_name)
            if not isinstance(metric_entry, dict):
                continue
            if metric_entry.get("tier_demoted_to") == perf_tier_registry.TIER_2:
                demotions.append({
                    "run_id": run_id,
                    "benchmark": bench_name,
                    "min": metric_entry.get("min"),
                    "max": metric_entry.get("max"),
                    "spread": metric_entry.get("spread"),
                })
    return demotions


def _build_per_benchmark_breakdown(
    records: list[dict[str, Any]], metric_name: str,
) -> dict[str, dict[str, Any]]:
    """Per-benchmark comparison cells for `metric_name`: for each benchmark that carries
    at least one clean sample, whether it is *comparable* (2 or more distinct CPU models
    observed) and, if so, whether it *agrees* (observed minimum equals observed maximum
    across every one of its samples from every one of its models, no tolerance). Emitted
    in sorted benchmark order with each `per_model` sub-mapping in sorted CPU-model order,
    matching the coverage table's own sort discipline."""
    by_benchmark: dict[str, dict[str, list[float]]] = {}
    for (bench_name, model), values in _collect_metric_samples_by_benchmark_and_model(
        records, metric_name,
    ).items():
        if not values:
            continue
        by_benchmark.setdefault(bench_name, {})[model] = values

    per_benchmark: dict[str, dict[str, Any]] = {}
    for bench_name in sorted(by_benchmark):
        models = by_benchmark[bench_name]
        pooled = [value for values in models.values() for value in values]
        comparable = len(models) >= 2
        bench_min = min(pooled)
        bench_max = max(pooled)
        per_benchmark[bench_name] = {
            "comparable": comparable,
            "agrees": comparable and bench_min == bench_max,
            "n": len(pooled),
            "minimum": bench_min,
            "maximum": bench_max,
            "spread": bench_max - bench_min,
            "cpu_models": sorted(models),
            "per_model": {
                model: {
                    "n": len(values),
                    "minimum": min(values),
                    "maximum": max(values),
                    "median": statistics.median(values),
                }
                for model, values in sorted(models.items())
            },
        }
    return per_benchmark


def build_invariance_section(records: list[dict[str, Any]]) -> dict[str, Any]:
    """Cross-CPU-model invariance verdicts.

    Every metric whose registry `direction` is `DIRECTION_INVARIANT` is evaluated
    regardless of the candidate tier its committed records happen to carry (a metric a
    prior campaign already demoted still carries that demoted candidate tier on every
    record it emits afterward, so gating eligibility on candidate tier would make any
    correction to the comparison itself permanent against that population). A metric
    whose direction is not invariant has no meaningful exact-equality comparison (there is
    nothing "invariant" about a continuous metric to test) and is never compared.

    The exact-equality bar is applied per benchmark across CPU models, not pooled
    across benchmarks: a benchmark is *comparable* when it carries samples from 2 or more
    distinct CPU models, and it *agrees* when its observed minimum equals its observed
    maximum across every sample from every one of its models, with no tolerance,
    percentage band, or rounding step anywhere in this path. Pooling every benchmark's
    samples into one list before comparing (the prior implementation) meant a metric
    collected on several benchmarks with legitimately differing counts could never pass
    the bar however deterministic each individual benchmark's cell was -- that defect is
    what this per-benchmark grouping corrects. The metric's verdict is bit-identical when
    at least one benchmark is comparable and every comparable benchmark agrees, demoted
    when any comparable benchmark disagrees, and insufficient-samples when no benchmark is
    comparable (a metric observed on only one CPU model demonstrates nothing about
    cross-model invariance, however many samples that one model contributed). A metric the
    harness already demoted within a single run binds at Tier 2 regardless of what
    cross-model agreement would otherwise show: within-run nondeterminism is strictly
    stronger evidence against Tier 1 than cross-model agreement is evidence for it.
    The binding tier lives under its own key here, never merged into or read back from the
    registry's candidate tier; the recorded candidate tier itself is reported
    separately, in `build_metric_section`'s own `tier_candidate` field, sourced from the
    records exactly as before.
    """
    observed_models = sorted({_cpu_model_of(record) for record in records})
    coverage = {
        "observed_cpu_models": observed_models,
        "observed_count": len(observed_models),
        "phase_2_observed_cpu_models": list(PHASE_2_OBSERVED_CPU_MODELS),
        "phase_2_observed_count": len(PHASE_2_OBSERVED_CPU_MODELS),
        "reduced_coverage": len(observed_models) < len(PHASE_2_OBSERVED_CPU_MODELS),
    }

    metrics_out: dict[str, Any] = {}
    for name in sorted(perf_tier_registry.METRICS):
        tier_candidates = _collect_metric_tier_candidates(records, name)
        candidate_tier = tier_candidates[0] if tier_candidates else TIER_CANDIDATE_NOT_RECORDED

        if perf_tier_registry.METRICS[name]["direction"] != perf_tier_registry.DIRECTION_INVARIANT:
            metrics_out[name] = {
                "verdict": NOT_APPLICABLE_NOT_INVARIANT,
                "binding_tier": candidate_tier,
            }
            continue

        within_run_demotions = _collect_within_run_demotions(records, name)
        if within_run_demotions:
            metrics_out[name] = {
                "verdict": CROSS_MODEL_VERDICT_WITHIN_RUN_DEMOTED,
                "binding_tier": perf_tier_registry.TIER_2,
                "within_run_demotions": within_run_demotions,
                "note": (
                    "a within-run bit-identical failure is strictly stronger evidence "
                    "against Tier 1 than cross-model agreement is evidence for it (D-12); "
                    "this metric binds at Tier 2 regardless of the cross-model comparison"
                ),
            }
            continue

        per_benchmark = _build_per_benchmark_breakdown(records, name)

        if not per_benchmark:
            metrics_out[name] = {
                "verdict": NOT_YET_DETERMINED,
                "binding_tier": NOT_YET_DETERMINED,
                "note": "no accepted record carries a clean sample for this invariant-direction metric",
            }
            continue

        observed_cpu_models = sorted(
            {model for entry in per_benchmark.values() for model in entry["cpu_models"]}
        )
        comparable_benchmarks = {
            bench: entry for bench, entry in per_benchmark.items() if entry["comparable"]
        }

        if not comparable_benchmarks:
            metrics_out[name] = {
                "verdict": INSUFFICIENT_SAMPLES,
                "binding_tier": NOT_YET_DETERMINED,
                "observed_cpu_models": observed_cpu_models,
                "per_benchmark": per_benchmark,
                "note": (
                    "no benchmark carrying a clean sample for this metric was observed on "
                    "2 or more CPU models; one model satisfies an "
                    "equal-minimum-and-maximum comparison trivially while demonstrating "
                    "nothing about cross-model invariance"
                ),
            }
            continue

        disagreeing = {
            bench: entry for bench, entry in comparable_benchmarks.items() if not entry["agrees"]
        }

        if not disagreeing:
            metrics_out[name] = {
                "verdict": CROSS_MODEL_VERDICT_BIT_IDENTICAL,
                "binding_tier": perf_tier_registry.TIER_1,
                "observed_cpu_models": observed_cpu_models,
                "per_benchmark": per_benchmark,
            }
        else:
            # The disagreeing-only minimum/maximum/spread are derived directly from each
            # disagreeing benchmark's own "minimum"/"maximum" cell rather than re-walking
            # raw samples: each of those cells already covers every sample from every one
            # of that benchmark's models.
            disagreeing_minima = [entry["minimum"] for entry in disagreeing.values()]
            disagreeing_maxima = [entry["maximum"] for entry in disagreeing.values()]
            demoted_min = min(disagreeing_minima)
            demoted_max = max(disagreeing_maxima)
            metrics_out[name] = {
                "verdict": CROSS_MODEL_VERDICT_DEMOTED,
                "binding_tier": perf_tier_registry.TIER_2,
                "observed_cpu_models": observed_cpu_models,
                "minimum": demoted_min,
                "maximum": demoted_max,
                "spread": demoted_max - demoted_min,
                "per_benchmark": per_benchmark,
                "note": (
                    "minimum/maximum/spread above are scoped to the disagreeing "
                    "benchmark(s) only, not pooled across every benchmark this metric was "
                    "measured on; see per_benchmark for the agreeing benchmarks' own cells"
                ),
            }

    return {"coverage": coverage, "metrics": metrics_out}


def build_metric_section(
    records: list[dict[str, Any]],
    min_n: int,
    mde_z: float = DEFAULT_PROVISIONAL_MDE_Z,
    mde_gate_pct: float = DEFAULT_MDE_GATE_PCT,
) -> dict[str, Any]:
    """One row per registry metric: its candidate tier (read from the accepted records'
    own emitted `tier_candidate` values, never from the live registry), the pooled
    sample count, median, MAD, coefficient of variation, minimum, maximum, the
    authoritative two-sample MDE, and Phase 1's provisional one-sample MDE computed
    through the identical `perf_noise_report.provisional_mde` code path Phase 1's own
    report used. Every statistic below `min_n` is suppressed to INSUFFICIENT_SAMPLES
    with a recorded `reason` rather than stating a value computed from too few samples,
    and no cell ever carries a `mean` key, since a mean is misleading precision on a
    distribution this noise-prone."""
    rows: dict[str, Any] = {}
    for name in sorted(perf_tier_registry.METRICS):
        samples = _collect_metric_samples(records, name)
        n = len(samples)
        tier_candidates = _collect_metric_tier_candidates(records, name)
        tier_candidate = tier_candidates[0] if tier_candidates else TIER_CANDIDATE_NOT_RECORDED

        row: dict[str, Any] = {"tier_candidate": tier_candidate, "n": n}

        # min_n is caller-supplied and can be zero or negative, so the zero-sample case
        # must be tested on its own: otherwise it can reach perf_noise_report.dispersion()
        # and two_sample_mde_pct(), which both raise on an empty/zero-length input.
        if n == 0 or n < min_n:
            for key in (
                "median", "mad", "cv", "minimum", "maximum",
                "mde_two_sample_pct", "mde_one_sample_provisional_pct",
            ):
                row[key] = INSUFFICIENT_SAMPLES
            row["non_gating"] = None
            reasons = _collect_metric_status_reasons(records, name)
            if n == 0:
                row["reason"] = (
                    "; ".join(reasons) if reasons
                    else "no accepted record carries a clean sample for this metric"
                )
            else:
                prefix = "; ".join(reasons) + "; " if reasons else ""
                row["reason"] = (
                    f"{prefix}only {n} clean sample(s) recorded, below the configured "
                    f"minimum of {min_n}"
                )
        else:
            stats = perf_noise_report.dispersion(samples)
            row["median"] = stats["median"]
            row["mad"] = stats["mad"]
            row["cv"] = stats["cv"]
            row["minimum"] = stats["minimum"]
            row["maximum"] = stats["maximum"]
            cv = stats["cv"]
            if isinstance(cv, (int, float)) and not isinstance(cv, bool):
                mde_two_sample = two_sample_mde_pct(cv, n)
                row["mde_two_sample_pct"] = mde_two_sample
                row["mde_one_sample_provisional_pct"] = perf_noise_report.provisional_mde(cv, n, mde_z)
                row["non_gating"] = mde_two_sample > mde_gate_pct
            else:
                row["mde_two_sample_pct"] = cv
                row["mde_one_sample_provisional_pct"] = cv
                row["non_gating"] = None
        rows[name] = row
    return rows


def build_source_coverage_section(records: list[dict[str, Any]]) -> dict[str, Any]:
    """One row per metric family named in the tier registry, naming the
    counter or getter that supplies it and whether any accepted record
    carries a clean sample for it, seeded from the registry's own family
    and source fields so this table cannot drift from the registry.
    `registry_note` carries REQUIRED_METRIC_FAMILIES' UNCOVERED_FAMILIES reason for a
    family the registry itself records a coverage caveat for, so this table cannot drift
    from that registry-level note either."""
    families: dict[str, dict[str, Any]] = {}
    for name in sorted(perf_tier_registry.METRICS):
        descriptor = perf_tier_registry.METRICS[name]
        family = descriptor["family"]
        entry = families.setdefault(family, {
            "source": descriptor["source"],
            "metrics": [],
            "covered": False,
        })
        entry["metrics"].append(name)
        if _collect_metric_samples(records, name):
            entry["covered"] = True

    coverage: dict[str, Any] = {}
    for family in sorted(families):
        entry = families[family]
        coverage[family] = {
            "source": entry["source"],
            "metrics": sorted(entry["metrics"]),
            "status": "covered" if entry["covered"] else "uncovered",
            "reason": (
                None if entry["covered"]
                else "no accepted harness record carries a clean sample for any metric in this family"
            ),
            "registry_note": perf_tier_registry.UNCOVERED_FAMILIES.get(family),
        }
    return coverage


def _round_floats(stats: dict[str, Any]) -> dict[str, Any]:
    """Round every float value in `stats` through this module's own `fmt_float`,
    leaving every non-float value (including sentinel strings) untouched -- matching
    scripts/probe_capability_report.py's own `_round_floats` convention."""
    return {
        key: (float(fmt_float(value)) if isinstance(value, float) else value)
        for key, value in stats.items()
    }


def _dispersion_cell(values: list[float], min_n: int) -> dict[str, Any]:
    """The shared median/MAD/CV/min/max dispersion set (never a mean, since a mean is
    misleading precision on a distribution this noise-prone), suppressed to
    INSUFFICIENT_SAMPLES below `min_n` or when `values` is empty."""
    n = len(values)
    if n == 0 or n < min_n:
        return {
            "n": n, "median": INSUFFICIENT_SAMPLES, "mad": INSUFFICIENT_SAMPLES,
            "cv": INSUFFICIENT_SAMPLES, "minimum": INSUFFICIENT_SAMPLES,
            "maximum": INSUFFICIENT_SAMPLES,
        }
    stats = perf_noise_report.dispersion(values)
    return {
        "n": n, "median": stats["median"], "mad": stats["mad"], "cv": stats["cv"],
        "minimum": stats["minimum"], "maximum": stats["maximum"],
    }


def _numeric(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _numeric_component_median(record: dict[str, Any], component: str) -> float | None:
    """The recorded calibration component's own median for this record (its
    k-times-measured-and-median-used figure), or None when unreadable or exactly zero --
    a zero divisor never produces a ratio."""
    environment = record.get("environment")
    environment = environment if isinstance(environment, dict) else {}
    calibration = environment.get("calibration_vector")
    calibration = calibration if isinstance(calibration, dict) else {}
    components = calibration.get("components")
    components = components if isinstance(components, dict) else {}
    component_entry = components.get(component)
    if not isinstance(component_entry, dict):
        return None
    median = component_entry.get("median")
    if _numeric(median) and median != 0.0:
        return float(median)
    return None


def _collect_flattening_values(
    records: list[dict[str, Any]], base_metric: str, component: str,
) -> tuple[dict[str, list[float]], dict[str, list[float]]]:
    """The raw metric's samples and the normalized ratio (each sample divided by that
    same record's own calibration component median), both pooled by the recording
    record's CPU model. A record whose component median is unreadable contributes to
    `raw_by_host` but not `ratio_by_host` -- a missing divisor drops the ratio sample,
    never fabricates one."""
    raw_by_host: dict[str, list[float]] = {}
    ratio_by_host: dict[str, list[float]] = {}
    for record in records:
        model = _cpu_model_of(record)
        component_median = _numeric_component_median(record, component)
        benchmarks = record.get("benchmarks")
        if not isinstance(benchmarks, dict):
            continue
        for bench_name in sorted(benchmarks):
            entry = benchmarks[bench_name]
            if not isinstance(entry, dict):
                continue
            metrics = entry.get("metrics")
            if not isinstance(metrics, dict):
                continue
            metric_entry = metrics.get(base_metric)
            if not isinstance(metric_entry, dict):
                continue
            for sample in metric_entry.get("samples", []):
                if not _numeric(sample):
                    continue
                raw_by_host.setdefault(model, []).append(float(sample))
                if component_median is not None:
                    ratio_by_host.setdefault(model, []).append(float(sample) / component_median)
    return raw_by_host, ratio_by_host


def _evaluate_pairing(
    raw_within: dict[str, Any], raw_across: dict[str, Any],
    ratio_within: dict[str, Any], ratio_across: dict[str, Any],
) -> tuple[Any, str]:
    """The two-sided qualification test: a pairing qualifies only if it measurably
    reduces across-host dispersion and does not inflate within-host dispersion. Returns
    INSUFFICIENT_SAMPLES, never a guessed True/False, when any of the four inputs is
    itself a marker rather than a number."""
    raw_within_cv = raw_within.get("within_cv")
    ratio_within_cv = ratio_within.get("within_cv")
    raw_across_cv = raw_across.get("cv")
    ratio_across_cv = ratio_across.get("cv")
    if not (
        _numeric(raw_within_cv) and _numeric(ratio_within_cv)
        and _numeric(raw_across_cv) and _numeric(ratio_across_cv)
    ):
        return INSUFFICIENT_SAMPLES, "insufficient samples to evaluate this pairing"

    reduces_across = ratio_across_cv < raw_across_cv
    inflates_within = ratio_within_cv > raw_within_cv
    if reduces_across and not inflates_within:
        return True, "reduces across-host dispersion without inflating within-host dispersion"
    if not reduces_across:
        return False, "does not reduce across-host dispersion"
    return False, "reduces across-host dispersion but inflates within-host dispersion"


def build_flattening_section(records: list[dict[str, Any]], min_n: int) -> dict[str, Any]:
    """Calibration flattening analysis.

    For every candidate base metric in `tests/perf/_perf_harness.DUAL_CLOCK_METRIC_NAMES`
    and every calibration component, computes the raw metric's and the normalized
    ratio's within-host dispersion (`perf_noise_report.variance_split`, pooled across
    host groups) and across-host dispersion (`perf_noise_report.dispersion` over
    per-host medians -- a single observed host suppresses through that function's own
    `n < 2` branch, never a new special case), then applies the two-sided qualification
    test. Every pairing's figures are recorded whether it qualifies or not, so a reader
    can see why a pairing was rejected. When no pairing qualifies for a metric, that is
    recorded as the finding: the normalized ratio stays collected and published
    for trend value, marked explicitly non-gating, and host stratification of the
    baseline is named as the remedy that actually works. The chosen pairing, when one
    qualifies, is the qualifying component with the smallest across-host CV.
    """
    result: dict[str, Any] = {}
    for base in sorted(_perf_harness.DUAL_CLOCK_METRIC_NAMES):
        pairings: dict[str, Any] = {}
        qualifying: list[tuple[str, Any]] = []

        for component in perf_tier_registry.CALIBRATION_COMPONENTS:
            raw_by_host, ratio_by_host = _collect_flattening_values(records, base, component)

            raw_within = perf_noise_report.suppress_below_min_n(
                _round_floats(perf_noise_report.variance_split(raw_by_host)), min_n,
            )
            ratio_within = perf_noise_report.suppress_below_min_n(
                _round_floats(perf_noise_report.variance_split(ratio_by_host)), min_n,
            )
            raw_host_medians = [statistics.median(v) for v in raw_by_host.values() if v]
            ratio_host_medians = [statistics.median(v) for v in ratio_by_host.values() if v]
            raw_across = _dispersion_cell(raw_host_medians, min_n)
            ratio_across = _dispersion_cell(ratio_host_medians, min_n)

            qualifies, reason = _evaluate_pairing(raw_within, raw_across, ratio_within, ratio_across)
            pairings[component] = {
                "raw_within": raw_within,
                "raw_across": raw_across,
                "ratio_within": ratio_within,
                "ratio_across": ratio_across,
                "qualifies": qualifies,
                "reason": reason,
            }
            if qualifies is True:
                qualifying.append((component, ratio_across.get("cv")))

        if qualifying:
            chosen = sorted(
                qualifying,
                key=lambda item: (item[1] if _numeric(item[1]) else math.inf, item[0]),
            )[0][0]
            note = (
                f"{chosen!r} measurably reduces across-host dispersion without inflating "
                f"within-host dispersion; the normalized ratio against it is the Tier 2 "
                f"gating candidate for {base}."
            )
        else:
            chosen = None
            note = (
                "No calibration pairing measurably reduced across-host dispersion without "
                "inflating within-host dispersion (D-14); the normalized ratio is still "
                "collected and published for trend value but marked non-gating. Host "
                "stratification of the baseline (docs/plans/perf-ci-hardening/"
                "NOISE-FLOOR-REPORT.md's pooled-to-stratified shrink table) is the remedy "
                f"that actually works for {base}."
            )

        result[base] = {
            "pairings": pairings,
            "chosen_pairing": chosen,
            "non_gating": chosen is None,
            "note": note,
        }

    return {"metrics": result}


def build_contamination_section(records: list[dict[str, Any]]) -> dict[str, Any]:
    """Contamination and INCONCLUSIVE evidence, per run.

    For every accepted record (the full population, including any injected-load run --
    this is the one section meant to show that run's evidence, not exclude it), reports
    the count of rejected samples with their reasons, the count of metrics that reported
    INCONCLUSIVE with their reasons, and the tally of secondary steal/cgroup flags across
    every sampled measurement window. Rejection-threshold derivations are quoted
    verbatim from tests/perf/_perf_harness.py's own module-level derivation strings
    rather than restated as numbers, so the report and the code cannot disagree.
    """
    thresholds = {
        "mad_band_derivation": _perf_harness.MAD_BAND_DERIVATION,
        "steal_derivation": _perf_harness.STEAL_DELTA_THRESHOLD_DERIVATION,
    }

    runs: dict[str, Any] = {}
    any_secondary_flag = False

    for record in records:
        run_id = record.get("_run_id", MISSING_FIELD)
        rejected_reasons: dict[str, int] = {}
        rejected_count = 0
        inconclusive_reasons: dict[str, int] = {}
        inconclusive_count = 0
        secondary_flag_counts: dict[str, int] = {}

        benchmarks = record.get("benchmarks")
        if isinstance(benchmarks, dict):
            for bench_name in sorted(benchmarks):
                entry = benchmarks[bench_name]
                if not isinstance(entry, dict):
                    continue
                metrics = entry.get("metrics")
                if isinstance(metrics, dict):
                    for metric_entry in metrics.values():
                        if not isinstance(metric_entry, dict):
                            continue
                        for rejected in metric_entry.get("rejected_samples", []) or []:
                            if not isinstance(rejected, dict):
                                continue
                            reason = rejected.get("reason", MISSING_FIELD)
                            rejected_reasons[reason] = rejected_reasons.get(reason, 0) + 1
                            rejected_count += 1
                        if metric_entry.get("status") == _perf_harness.STATUS_INCONCLUSIVE:
                            reason = metric_entry.get("reason", MISSING_FIELD)
                            inconclusive_reasons[reason] = inconclusive_reasons.get(reason, 0) + 1
                            inconclusive_count += 1
                windows = entry.get("measurement_windows")
                if isinstance(windows, list):
                    for window in windows:
                        if not isinstance(window, dict):
                            continue
                        for flag in window.get("secondary_flags", []) or []:
                            secondary_flag_counts[flag] = secondary_flag_counts.get(flag, 0) + 1
                            any_secondary_flag = True

        injected = is_injected_load_run(record)
        runs[run_id] = {
            "is_injected_demonstration": injected,
            "label": INJECTED_DEMONSTRATION if injected else None,
            "rejected_sample_count": rejected_count,
            "rejected_reasons": dict(sorted(rejected_reasons.items())),
            "inconclusive_metric_count": inconclusive_count,
            "inconclusive_reasons": dict(sorted(inconclusive_reasons.items())),
            "secondary_flag_counts": dict(sorted(secondary_flag_counts.items())),
        }

    return {
        "thresholds": thresholds,
        "runs": runs,
        "observed_any_secondary_contention": any_secondary_flag,
        "note": (
            "This campaign observed no secondary steal or cgroup contention flag at all "
            "(D-11): the rejection path's behaviour under real steal is therefore "
            "untested, not validated."
        ) if not any_secondary_flag else (
            "This campaign observed at least one secondary steal or cgroup contention "
            "flag; see secondary_flag_counts per run."
        ),
    }


def build_sidecar(
    *,
    population: dict[str, Any],
    min_n: int,
    expected_tree_hash: str | None,
    runs_dir: str,
    noise_floor_path: str | Path = DEFAULT_NOISE_FLOOR_PATH,
) -> dict[str, Any]:
    accepted = population["accepted"]
    # A run dispatched with its injected-load input set is excluded from every
    # dispersion, invariance, and minimum-detectable-effect figure -- laundering it into
    # the precision numbers would defeat the demonstration's whole purpose. It is still
    # visible in the contamination section and in the population accounting below.
    injected_records = [record for record in accepted if is_injected_load_run(record)]
    clean_records = [record for record in accepted if not is_injected_load_run(record)]

    noise_floor_params = load_noise_floor_parameters(Path(noise_floor_path))
    metrics = build_metric_section(
        clean_records, min_n,
        mde_z=noise_floor_params["mde_z"], mde_gate_pct=noise_floor_params["mde_gate_pct"],
    )
    non_gating_metrics = sorted(
        name for name, row in metrics.items() if row.get("non_gating") is True
    )
    return {
        "sidecar_version": SIDECAR_VERSION,
        "source": {
            "runs_dir": runs_dir,
            "expected_tree_hash": expected_tree_hash,
            "record_count": len(accepted),
            "records_skipped": population["records_skipped"],
            "records_rejected": population["records_rejected"],
            "records_injected_demonstration": len(injected_records),
            "record_count_clean": len(clean_records),
            "injected_demonstration_run_ids": sorted(
                record.get("_run_id", MISSING_FIELD) for record in injected_records
            ),
            "noise_floor_parameters": noise_floor_params,
            "reconciliation_doc": RECONCILIATION_DOC,
        },
        "metrics": metrics,
        "non_gating_metrics": non_gating_metrics,
        "source_coverage": build_source_coverage_section(clean_records),
        "invariance": build_invariance_section(clean_records),
        "flattening": build_flattening_section(clean_records, min_n),
        "contamination": build_contamination_section(accepted),
    }


def _cell(value: Any) -> str:
    """Render `value` for a markdown cell, `n/a` for `None` (an absent, never-computed
    figure) rather than the literal string `None`."""
    if value is None:
        return "n/a"
    return fmt_float(value)


def _binding_tier_for(sidecar: dict[str, Any], name: str) -> Any:
    """The binding tier for `name`, sourced only from the invariance section's own
    per-metric `binding_tier`, never falling back to the candidate column: a candidate
    tier is only a hypothesis pending cross-model comparison, not evidence.
    `NOT_YET_DETERMINED` when that section has not computed one for this metric yet."""
    invariance = sidecar.get("invariance", {})
    metrics = invariance.get("metrics", {})
    entry = metrics.get(name, {})
    if not isinstance(entry, dict):
        return NOT_YET_DETERMINED
    return entry.get("binding_tier", NOT_YET_DETERMINED)


def render_markdown(sidecar: dict[str, Any]) -> str:
    source = sidecar["source"]
    noise_floor = source["noise_floor_parameters"]
    lines = [
        "<!-- generated by scripts/perf_campaign_report.py, do not edit by hand -->",
        "# Perf Harness Campaign Report",
        "",
        "## Reproducing this report",
        "",
        "```sh",
        CANONICAL_COMMAND,
        "```",
        "",
        "## Source",
        "",
        f"- Runs directory: `{source['runs_dir']}`",
        f"- Expected tree hash: `{source['expected_tree_hash']}`",
        f"- Records accepted: {source['record_count']}",
        f"- Records skipped (malformed/unrecognized schema): {source['records_skipped']}",
        f"- Records rejected (tree hash mismatch): {source['records_rejected']}",
        f"- Records dispatched as an injected-load demonstration (D-10): "
        f"{source['records_injected_demonstration']} "
        f"({', '.join(source['injected_demonstration_run_ids']) or 'none'}), excluded from "
        "every metrics/invariance/flattening figure below but shown in the contamination "
        "section",
        f"- Clean records feeding the metrics/invariance/flattening sections: "
        f"{source['record_count_clean']}",
        "- Noise floor parameters (min_n, mde_z, mde_gate_pct) source: "
        f"`{noise_floor['source_file']}` (loaded={noise_floor['loaded']}): "
        f"min_n={fmt_float(noise_floor['min_n'])}, mde_z={fmt_float(noise_floor['mde_z'])}, "
        f"mde_gate_pct={fmt_float(noise_floor['mde_gate_pct'])}",
        f"- Criteria and requirement reconciliation: `{RECONCILIATION_DOC}`",
        "",
        "## Minimum detectable effect: two figures, not a silent recomputation",
        "",
        "Two MDE figures are reported side by side for every metric (D-32). "
        "`mde_two_sample_pct` is the authoritative figure: a two-sample current-versus-"
        "baseline comparison, `(Z_ALPHA_2 + Z_BETA) * sqrt(2 / n) * cv * 100`, carrying "
        "both a 95% confidence term and an 80% power term, because the gate itself "
        "compares a candidate run against a baseline. `mde_one_sample_provisional_pct` "
        "is Phase 1's provisional figure computed through the identical "
        "`perf_noise_report.provisional_mde` code path Phase 1's own report used: a "
        "one-sample confidence-interval half-width with no power term "
        "(`z * cv * 100 / sqrt(n)`), explicitly labelled provisional and non-binding in "
        "`NOISE-FLOOR-REPORT.md`'s \"Provisional minimum detectable effect (non-binding)\" "
        "section. The authoritative figure is larger than the provisional one by roughly "
        "a factor of two at this campaign's sample count: a threshold tuned against the "
        "provisional figure would have been tuned against an optimistic bound.",
        "",
        "## Metrics",
        "",
        "One row per registry metric. A cell reading "
        f"`{INSUFFICIENT_SAMPLES}` means fewer than the configured minimum sample count "
        "were available across the accepted population, never a fabricated value. "
        "`Candidate tier` is read from each accepted record's own emitted "
        "`tier_candidate` value, never from the live registry (D-30): mutating "
        "`scripts/perf_tier_registry.py` after this population is committed cannot "
        f"change a byte of this report. A cell reading `{TIER_CANDIDATE_NOT_RECORDED}` "
        "means no accepted record ever measured this metric. `Binding tier` is populated "
        "only from the cross-CPU-model invariance section below; a cell reading "
        f"`{NOT_YET_DETERMINED}` means that section has not yet computed a verdict for "
        "this metric.",
        "",
        "| Metric | Candidate tier | Binding tier | n | Median | MAD | CV | Min | Max | "
        "MDE two-sample (%) | MDE one-sample provisional (%) | Non-gating | Reason |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name in sorted(sidecar["metrics"]):
        row = sidecar["metrics"][name]
        binding_tier = _binding_tier_for(sidecar, name)
        lines.append(
            "| " + name
            + " | " + fmt_float(row["tier_candidate"])
            + " | " + fmt_float(binding_tier)
            + " | " + str(row["n"])
            + " | " + fmt_float(row["median"])
            + " | " + fmt_float(row["mad"])
            + " | " + fmt_float(row["cv"])
            + " | " + fmt_float(row["minimum"])
            + " | " + fmt_float(row["maximum"])
            + " | " + fmt_float(row["mde_two_sample_pct"])
            + " | " + fmt_float(row["mde_one_sample_provisional_pct"])
            + " | " + _cell(row.get("non_gating"))
            + " | " + (row.get("reason") or "")
            + " |"
        )
    lines.append("")

    non_gating_names = sidecar.get("non_gating_metrics", [])
    lines.extend([
        "## Non-gating metrics (MDE too large to gate)",
        "",
        "VALID-06: a metric whose two-sample MDE exceeds the provisional gate percentage "
        "recorded in Phase 1's sidecar is named here explicitly and marked non-gating, "
        "rather than left for a reader to infer non-gateability from the number alone.",
        "",
    ])
    if non_gating_names:
        lines.append("| Metric | MDE two-sample (%) | Gate (%) |")
        lines.append("|---|---|---|")
        for name in non_gating_names:
            row = sidecar["metrics"][name]
            lines.append(
                f"| {name} | {fmt_float(row['mde_two_sample_pct'])} | "
                f"{fmt_float(noise_floor['mde_gate_pct'])} |"
            )
    else:
        lines.append(
            "No metric's two-sample MDE currently exceeds the provisional gate percentage."
        )
    lines.append("")

    lines.extend([
        "## Source coverage",
        "",
        "One row per metric family named in the tier registry, seeded from the registry's "
        "own family and source fields so this table cannot drift from it.",
        "",
        "| Family | Source | Metrics | Status | Reason |",
        "|---|---|---|---|---|",
    ])
    for family in sorted(sidecar["source_coverage"]):
        entry = sidecar["source_coverage"][family]
        lines.append(
            "| " + family
            + " | `" + entry["source"] + "`"
            + " | " + ", ".join(entry["metrics"])
            + " | " + entry["status"]
            + " | " + (entry["reason"] or "")
            + " |"
        )
    lines.append("")

    invariance = sidecar["invariance"]
    coverage = invariance["coverage"]
    lines.extend([
        "## Cross-CPU-model invariance",
        "",
        "Every invariant-direction metric's invariance verdict is derived from an exact "
        "minimum-equals-maximum comparison applied per benchmark across every observed CPU "
        "model, with no tolerance, percentage band, or rounding step (D-31). Pooling every "
        "benchmark's samples into one list before comparing would make a metric collected "
        "on several benchmarks with legitimately differing counts unable to pass the bar "
        "however deterministic each individual benchmark's cell was, so the comparison is "
        "scoped to one benchmark at a time instead. A benchmark with fewer than 2 observed "
        "CPU models is not comparable and contributes nothing toward the verdict; a metric "
        "with no comparable benchmark at all "
        f"reports `{INSUFFICIENT_SAMPLES}` rather than a trivially-satisfied "
        "bit-identical verdict: one model demonstrates nothing about cross-model "
        "invariance. A metric the harness already demoted within a single run binds at "
        "Tier 2 regardless of what cross-model agreement would otherwise show (D-12). A "
        "metric whose registry direction is not invariant is never compared at all.",
        "",
        f"- CPU models observed by this campaign: {coverage['observed_count']} "
        f"({', '.join(coverage['observed_cpu_models']) or 'none'})",
        f"- CPU models Phase 2 observed: {coverage['phase_2_observed_count']} "
        f"({', '.join(coverage['phase_2_observed_cpu_models'])})",
        "- Reduced coverage relative to Phase 2: "
        + ("yes -- invariance verdicts below are bounded by the models actually seen"
           if coverage["reduced_coverage"] else "no"),
        "",
        "| Metric | Candidate tier | Verdict | Binding tier | Observed models | Min | Max | Spread |",
        "|---|---|---|---|---|---|---|---|",
    ])
    for name in sorted(invariance["metrics"]):
        entry = invariance["metrics"][name]
        candidate = sidecar["metrics"].get(name, {}).get("tier_candidate", TIER_CANDIDATE_NOT_RECORDED)
        observed = entry.get("observed_cpu_models")
        lines.append(
            "| " + name
            + " | " + fmt_float(candidate)
            + " | " + fmt_float(entry.get("verdict"))
            + " | " + fmt_float(entry.get("binding_tier"))
            + " | " + (", ".join(observed) if observed else "")
            + " | " + _cell(entry.get("minimum"))
            + " | " + _cell(entry.get("maximum"))
            + " | " + _cell(entry.get("spread"))
            + " |"
        )
    lines.append("")

    multi_benchmark_metrics = sorted(
        name for name, entry in invariance["metrics"].items()
        if len([b for b in entry.get("per_benchmark", {}).values() if b["comparable"]]) > 1
    )
    if multi_benchmark_metrics:
        lines.extend([
            "### Per-benchmark breakdown",
            "",
            "Metrics compared on more than one comparable benchmark this campaign, shown "
            "one benchmark per row so a demoted metric's disagreeing benchmark is named "
            "directly rather than left to a pooled figure that mixes it with an agreeing "
            "one.",
            "",
        ])
        for name in multi_benchmark_metrics:
            entry = invariance["metrics"][name]
            lines.append(f"**{name}**")
            lines.append("")
            lines.append("| Benchmark | Comparable | Agrees | N | Min | Max | Spread | Models |")
            lines.append("|---|---|---|---|---|---|---|---|")
            for bench_name in sorted(entry["per_benchmark"]):
                cell = entry["per_benchmark"][bench_name]
                lines.append(
                    "| " + bench_name
                    + " | " + fmt_float(cell["comparable"])
                    + " | " + fmt_float(cell["agrees"])
                    + " | " + fmt_float(cell["n"])
                    + " | " + _cell(cell["minimum"])
                    + " | " + _cell(cell["maximum"])
                    + " | " + _cell(cell["spread"])
                    + " | " + ", ".join(cell["cpu_models"])
                    + " |"
                )
            lines.append("")

    flattening = sidecar["flattening"]
    lines.extend([
        "## Calibration flattening",
        "",
        "Per candidate base metric and per calibration component: whether normalizing "
        "the raw metric by that component's own median measurably reduces across-host "
        "dispersion without inflating within-host dispersion (D-13). A pairing qualifies "
        "only when both hold; every pairing's figures are shown whether it qualifies or "
        "not, so a reader can see why. When no pairing qualifies for a metric, that is "
        "the finding (D-14): the normalized ratio stays published for trend value, "
        "marked non-gating, and host stratification of the baseline is named as the "
        "remedy that works instead.",
        "",
        "| Base metric | Chosen pairing | Non-gating |",
        "|---|---|---|",
    ])
    for base in sorted(flattening["metrics"]):
        entry = flattening["metrics"][base]
        lines.append(
            f"| {base} | {_cell(entry['chosen_pairing'])} | {_cell(entry['non_gating'])} |"
        )
    lines.append("")
    for base in sorted(flattening["metrics"]):
        entry = flattening["metrics"][base]
        lines.extend([
            f"### {base}",
            "",
            entry["note"],
            "",
            "| Component | Qualifies | Reason | Raw within CV | Raw across CV | "
            "Ratio within CV | Ratio across CV |",
            "|---|---|---|---|---|---|---|",
        ])
        for component in perf_tier_registry.CALIBRATION_COMPONENTS:
            pairing = entry["pairings"][component]
            lines.append(
                "| " + component
                + " | " + _cell(pairing["qualifies"])
                + " | " + pairing["reason"]
                + " | " + _cell(pairing["raw_within"].get("within_cv"))
                + " | " + _cell(pairing["raw_across"].get("cv"))
                + " | " + _cell(pairing["ratio_within"].get("within_cv"))
                + " | " + _cell(pairing["ratio_across"].get("cv"))
                + " |"
            )
        lines.append("")

    contamination = sidecar["contamination"]
    lines.extend([
        "## Injected-load contamination",
        "",
        "Per accepted run (including any run labelled "
        f"`{INJECTED_DEMONSTRATION}`, which is excluded from every metrics/invariance/"
        "flattening figure above but shown here on purpose -- D-10): the count of "
        "rejected samples with their reasons, the count of metrics that reported "
        "INCONCLUSIVE with their reasons, and the tally of secondary steal/cgroup flags.",
        "",
        "Rejection threshold derivations, quoted verbatim from "
        "`tests/perf/_perf_harness.py` so the report and the code cannot disagree:",
        "",
        f"- MAD band: {contamination['thresholds']['mad_band_derivation']}",
        f"- Steal delta: {contamination['thresholds']['steal_derivation']}",
        "",
        contamination["note"],
        "",
        "| Run | Injected demonstration | Rejected samples | INCONCLUSIVE metrics | "
        "Secondary flags |",
        "|---|---|---|---|---|",
    ])
    for run_id in sorted(contamination["runs"]):
        run_entry = contamination["runs"][run_id]
        secondary = ", ".join(
            f"{flag}={count}" for flag, count in sorted(run_entry["secondary_flag_counts"].items())
        )
        lines.append(
            "| " + run_id
            + " | " + _cell(run_entry["is_injected_demonstration"])
            + " | " + str(run_entry["rejected_sample_count"])
            + " | " + str(run_entry["inconclusive_metric_count"])
            + " | " + secondary
            + " |"
        )
    lines.append("")

    return "\n".join(lines) + "\n"


def write_deterministic_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--runs-dir",
        default=DEFAULT_RUNS_DIR,
        help="Directory containing committed per-run harness JSON files",
    )
    parser.add_argument(
        "--expected-tree-hash",
        default=None,
        help="git rev-parse HEAD^{tree} the campaign is pinned to",
    )
    parser.add_argument(
        "--min-n",
        type=int,
        default=DEFAULT_MIN_N,
        help="Minimum sample count before a statistic is reported rather than suppressed",
    )
    parser.add_argument(
        "--out-md",
        default=DEFAULT_OUT_MD,
        help="Output path for the generated markdown report",
    )
    parser.add_argument(
        "--out-json",
        default=DEFAULT_OUT_JSON,
        help="Output path for the generated JSON sidecar",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    runs_dir = Path(args.runs_dir)
    paths = sorted(runs_dir.glob("*.json")) if runs_dir.is_dir() else []
    population = build_population(paths, args.expected_tree_hash)

    if not population["accepted"]:
        print(
            "No harness-run records survived population membership. "
            f"Skipped (malformed/unrecognized schema): {population['records_skipped']}, "
            f"Rejected (tree hash mismatch): {population['records_rejected']}"
        )
        return 1

    sidecar = build_sidecar(
        population=population,
        min_n=args.min_n,
        expected_tree_hash=args.expected_tree_hash,
        runs_dir=str(runs_dir),
    )
    markdown = render_markdown(sidecar)

    write_deterministic_json(Path(args.out_json), sidecar)
    out_md = Path(args.out_md)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(markdown, encoding="utf-8")

    return 0


if __name__ == "__main__":
    sys.exit(main())
# ----------------------------------------------------------------------------
